/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.6/samples
 */

plugins {
    // https://github.com/gradle-nexus/publish-plugin#user-content-applying-the-plugin
    id("io.github.gradle-nexus.publish-plugin") version "1.3.0"
}

group = "com.essaid.views.whistle"
version = "0.0.1-SNAPSHOT"

nexusPublishing {
    repositories {
        sonatype()
    }
}

